
export const USER_INFO = 'UserInfo'//用户信息

export const UPDATE_USER_LEVEL = 'UPDATE_USER_LEVEL'//会员信息
export const UPDATE_SHARE_LIST = 'UPDATE_SHARE_LIST'//推荐列表


export const UPDATE_HOUSE_MANAGE = 'UPDATE_HOUSE_MANAGE'//房源管理-全部
export const UPDATE_HOUSE_PENDING = 'UPDATE_HOUSE_PENDIN'//房源管理-待审核
export const UPDATE_HOUSE_RELEASED = 'UPDATE_HOUSE_RELEASED'//房源管理-已发布
export const UPDATE_HOUSE_TRADED = 'UPDATE_HOUSE_TRADED'//房源管理-已成交

export const LOGIN = 'LOGIN'//登录
export const LOGOUT = 'LOGOUT'//退出
export const WX_REGISTER = 'WX_REGISTER'//微信注册
export const UPDATE_LOGIN_STATE = 'UPDATE_LOGIN_STATE'//登录状态

export const UPDATE_USER_BUY_OPENID = 'UPDATE_USER_BUY_OPENID'//更新openID

export const UPDATE_USER_ARTICLE = 'UPDATE_USER_ARTICLE'//更新文章列表
export const UPDATE_RTICLE_DETAIL = 'UPDATE_RTICLE_DETAIL'//更新文章详情

export const UPDATE_CAROUSEL_LIST = 'UPDATE_CAROUSEL_LIST'//更新轮播图

export const UPDATE_MEMBER_INFO = 'UPDATE_MEMBER_INFO' //更新会员资料


export const WX_BIND = 'WX_BIND'//微信绑定
export const OLD_LOGIN = 'OLD_LOGIN'//登录

export const UPDATE_WECHAT_CODE = 'UPDATE_WECHAT_CODE'
export const UPDATE_WECHAT_STATE = 'UPDATE_WECHAT_STATE'
export const UPDATE_USER_OPENID = 'UPDATE_USER_OPENID'


export const REGISTER = 'REGISTER'//注册
export const REGISTER_PROTOCOL = 'REGISTER_PROTOCOL'//注册协议

export const UPDATE_LOADING = 'UPDATE_LOADING'//更新LOADING

export const UPDATE_LOCATION = 'UPDATE_LOCATION'//更新位置
export const UPDATE_AREA_CHILD = 'UPDATE_AREA_CHILD'//更新子级地区
export const UPDATE_AREA_CHILD_TWO = 'UPDATE_AREA_CHILD_TWO'//更新子级地区
export const UPDATE_AREA_BROTHER = 'UPDATE_AREA_BROTHER'//更新同级地区


export const UPDATE_LOCATION_ADDRESS = 'UPDATE_LOCATION_ADDRESS'//更新位置地址
export const UPDATE_LOCATION_TEACHER = 'UPDATE_LOCATION_TEACHER'//更新附近的老师
export const UPDATE_LOCATION_INFO = 'UPDATE_LOCATION_INFO'//获取附近的位置
export const UPDATE_NEARBY_ROOM = 'UPDATE_NEARBY_ROOM'//获取附近的门店


export const UPDATE_HOUSE_PRICE = 'UPDATE_HOUSE_PRICE'//获取价格条件
export const UPDATE_HOUSE_TYPE = 'UPDATE_HOUSE_TYPE'//获取装修类型
export const UPDATE_HOUSE_ORIENTATION = 'UPDATE_HOUSE_ORIENTATION'//获取朝向
export const UPDATE_HOUSE_AREA = 'UPDATE_HOUSE_AREA'//获取面积
export const UPDATE_HOUSE_FLOOR = 'UPDATE_HOUSE_FLOOR'//获取楼层
export const UPDATE_HOUSE_AGE = 'UPDATE_HOUSE_AGE'//获取楼龄
export const UPDATE_HOUSE_USE_RIGHTS = 'UPDATE_HOUSE_USE_RIGHTS'//获取产权用途
export const UPDATE_HOUSE_LAYOUT = 'UPDATE_HOUSE_LAYOUT'//获取房型
// export const UPDATE_HOUSE_LABEL = 'UPDATE_HOUSE_LABEL'//获取标签
export const UPDATE_RENTAL_LABEL = 'UPDATE_RENTAL_LABEL'//获取租房标签
export const UPDATE_RESOLD_LABEL = 'UPDATE_RESOLD_LABEL'//获取二手房标签


export const UPDATE_HOUSE_EQUIPMENT = 'UPDATE_HOUSE_EQUIPMENT'//获取配备设备
export const UPDATE_HOUSE_STRUCT = 'UPDATE_HOUSE_STRUCT'//获取房子结构
export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY'//获取小区列表

export const UPDATE_SELECT_PRICE = 'UPDATE_SELECT_PRICE'//获取价格条件
export const UPDATE_SELECT_TYPE = 'UPDATE_SELECT_TYPE'//获取装修类型
export const UPDATE_SELECT_ORIENTATION = 'UPDATE_SELECT_ORIENTATION'//获取朝向
export const UPDATE_SELECT_AREA = 'UPDATE_SELECT_AREA'//获取面积
export const UPDATE_SELECT_FLOOR = 'UPDATE_SELECT_FLOOR'//获取楼层
export const UPDATE_SELECT_AGE = 'UPDATE_SELECT_AGE'//获取楼龄
export const UPDATE_SELECT_USE_RIGHTS = 'UPDATE_SELECT_USE_RIGHTS'//获取产权用途
export const UPDATE_SELECT_LAYOUT = 'UPDATE_SELECT_LAYOUT'//获取房型
export const UPDATE_SELECT_LABEL = 'UPDATE_SELECT_LABEL'//获取标签
export const UPDATE_SELECT_EQUIPMENT = 'UPDATE_SELECT_EQUIPMENT'//获取配备设备

export const UPDATE_RENTAL_HOUSE = 'UPDATE_RENTAL_HOUSE'//租房
export const UPDATE_RESOLD_HOUSE = 'UPDATE_RESOLD_HOUSE'//二手房
export const UPDATE_NEW_HOUSE = 'UPDATE_NEW_HOUSE'//新房
export const UPDATE_RENTAL_HOUSE_INFO = 'UPDATE_RENTAL_HOUSE_INFO'//租房房源信息
export const UPDATE_RESOLD_HOUSE_INFO = 'UPDATE_RESOLD_HOUSE_INFO'// 二手房房源信息

export const UPDATE_RENT_CHANGE = 'UPDATE_RENT_CHANGE' //编辑租房
export const UPDATE_RESOLD_CHANGE = 'UPDATE_RESOLD_CHANGE' //编辑二手房

export const UPDATE_NEW_HOUSE_INFO = 'UPDATE_NEW_HOUSE_INFO'//新房房源信息
export const UPDATE_DETAIL_HOUSE_INFO = 'UPDATE_DETAIL_HOUSE_INFO'//房源信息详情
export const UPDATE_DETAIL_HOUSE_RECODE = 'UPDATE_DETAIL_HOUSE_RECODE' //房源信息备注
export const UPDATE_HOUSE_CONTRACT = 'UPDATE_HOUSE_CONTRACT' //房源合同
export const UPDATE_SCHEDULE_RECODE = 'UPDATE_SCHEDULE_RECODE' //房源合同

export const UPDATE_DETAIL_HOUSE_PAY = 'UPDATE_DETAIL_HOUSE_PAY' //房源详情价格

export const UPDATE_FILE_CALLBACK_A = 'UPDATE_FILE_CALLBACK_A' //文件返回a

export const UPDATE_FILE_CALLBACK_B = 'UPDATE_FILE_CALLBACK_B'//文件返回b

export const UPDATE_RENTAL_CONTRACT_LIST = 'UPDATE_RENTAL_CONTRACT_LIST'//房源合同出租
export const UPDATE_SELL_CONTRACT_LIST = 'UPDATE_SELL_CONTRACT_LIST'//房源合同出售

export const UPDATE_SELL_TAG = 'UPDATE_SELL_TAG' //售房标签
export const UPDATE_RENT_TAG = 'UPDATE_RENT_TAG'//租房标签
export const UPDATE_RENT_EQUIP = 'UPDATE_RENT_EQUIP'//租房家电配置





export const UPDATE_MESSAGES_DATA = 'UPDATE_MESSAGES_DATA'//更新消息内容
export const UPDATE_UNREADCOUNT = 'UPDATE_UNREADCOUNT'//获取未读消息数量
export const UPDATE_PUSH_MESSAGES = 'UPDATE_PUSH_MESSAGES'//获取推送消息
export const UPDATE_MESSAGES_CONTENT = 'UPDATE_MESSAGES_CONTENT'//获取推送消息



export const UPDATE_AUTH_MOBILE = 'UPDATE_AUTH_MOBILE'//更新授权手机号
export const UPDATE_AUTH_TYPE = 'UPDATE_AUTH_TYPE'//更新授权类型
export const UPDATE_AUTH_USERNAME = 'UPDATE_AUTH_USERNAME'//更新用户名

export const UPDATE_AUTH_SUBMIT_LOGIN = 'UPDATE_AUTH_SUBMIT_LOGIN'//提交登录




export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN'//更新用户TOKE
export const DELETE_USER_TOKEN = 'DELETE_USER_TOKEN'//更新用户TOKEN
export const UPDATE_USER_INFORMATION = 'UPDATE_USER_INFORMATION'//更新用户信息
export const UPDATE_USER_CREDIT = 'UPDATE_USER_CREDIT'//更新用户信用

export const UPDATE_SUBJECT_TYPE = 'UPDATE_SUBJECT_TYPE'//更新教育科目
export const UPDATE_ORDER_COUNT = 'UPDATE_ORDER_COUNT'//更新订单提示数量

export const UPDATE_CONTACTS_BOOK = 'UPDATE_CONTACTS_BOOK'//更新手机通讯录

// export const UPDATE_MY_COLLECTION = 'UPDATE_MY_COLLECTIONT'//更新我的收藏

export const UPDATE_RESOLD_COLLECTION = 'UPDATE_RESOLD_COLLECTION'//更新我的收藏-二手房
export const UPDATE_NEW_COLLECTION = 'UPDATE_NEW_COLLECTION'//更新我的收藏-新房
export const UPDATE_RENTAL_COLLECTION = 'UPDATE_RENTAL_COLLECTION'//更新我的收藏-租房

export const UPDATE_CREATE_RECOMMEND_CODE = 'UPDATE_CREATE_RECOMMEND_CODE'//创建我的推荐码
export const UPDATE_RECOMMEND_CODE = 'UPDATE_RECOMMEND_CODE'//更新我的推荐码
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR'//更新我的头像


export const UPDATE_CLIENT_RENT = 'UPDATE_CLIENT_RENT'  //更新客户管理-求租
export const UPDATE_CLIENT_SELL = 'UPDATE_CLIENT_SELL'  //更新客户管理-求购

export const UPDATE_MY_CLIENT_SELL = 'UPDATE_MY_CLIENT_SELL'  //更新我的客户-求租
export const UPDATE_MY_CLIENT_RENT = 'UPDATE_MY_CLIENT_RENT'  //更新我的客户-求购

export const UPDATE_SEE_LIST = 'UPDATE_SEE_LIST'  //更新我的客户-跟客维护

export const UPDATE_CLIENT_VIEWLOG = 'UPDATE_CLIENT_VIEWLOG' //更新看房记录
export const UPDATE_CLIENT_INFO = 'UPDATE_CLIENT_INFO' //更新客户信息
export const UPDATE_VIEW_LOG_DETAILL = 'UPDATE_VIEW_LOG_DETAILL'//更新看房详情

export const UPDATE_LOG_BALANCE = 'UPDATE_LOG_BALANCE'//更新财务日志
export const ADD_LOG_BALANCE = 'ADD_LOG_BALANCE'//增加财务日志
/* export const UPDATE_LOG_BALANCE_REFRESHING='ADD_LOG_BALANCE_REFRESHING'//增加财务日志加载提示
export const UPDATE_LOG_BALANCE_NODATA='UPDATE_LOG_BALANCE_NODATA'//设置没有数据
export const UPDATE_LOG_BALANCE_PAGE='UPDATE_LOG_BALANCE_PAGE'//设置页码 */

export const UPDATE_PAY_RECHARGE = 'UPDATE_PAY_RECHARGE'//更新特惠充值

export const UPDATE_SCANNER_DATA = 'UPDATE_SCANNER_DATA'//更新扫描内容
export const UPDATE_SCANNER_COUPON_INFO = 'UPDATE_SCANNER_COUPON_INFO'//更新扫描到的优惠券

export const UPDATE_BINDING_WEIXIN = 'UPDATE_BINDING_WEIXIN'//更新绑定微信

export const UPDATE_WX_LOAD = 'UPDATE_WX_LOAD'//更新微信JDK加载情况




// Action types to be dispatched by the user
export const WEBSOCKET_CONNECT = 'WEBSOCKET:CONNECT'
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET:DISCONNECT'
export const WEBSOCKET_SEND = 'WEBSOCKET:SEND'
// Action types dispatched by the WebSocket implementation
export const WEBSOCKET_CONNECTING = 'WEBSOCKET:CONNECTING'
export const WEBSOCKET_OPEN = 'WEBSOCKET:OPEN'
export const WEBSOCKET_DISCONNECTING = 'WEBSOCKET:DISCONNECTING'
export const WEBSOCKET_CLOSED = 'WEBSOCKET:CLOSED'
export const WEBSOCKET_MESSAGE = 'WEBSOCKET:MESSAGE'


export const incrementCounter = "INCREMENT_COUNTER";
export const decrementCounter = "DECREMENT_COUNTER";